@baseUrl = http://localhost:4000
@contentType = application/json
@token =eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJBcHBOYW1lIjoiQ2xpZW50QXBwIiwiUmVhZCI6InRydWUiLCJXcml0ZSI6InRydWUiLCJuYmYiOjE3NTgzMTUwMzUsImV4cCI6MTc1ODMxNTYzNX0.zWtfrratp_omu3EaIZ6Q3LqvecsqZeG1gJDoXfHPt5o


###
GET {{baseUrl}}/client
Authorization: Bearer {{token}}


###
POST {{baseUrl}}/authority/auth
Content-Type: {{contentType}}
{
  "username": "Client",
  "password": "1234"
}
