@baseUrl = http://localhost:4000
@contentType = application/json
@token =


###
GET {{baseUrl}}/client
Authorization: Bearer {{token}}


###
POST {{baseUrl}}/authority/auth
Content-Type: {{contentType}}
{
  "username": "Admin1",
  "password": "password"
}
